// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Bus_ETA

#ifndef _BUS_ETA_UI_H
#define _BUS_ETA_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Main.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_261349413);   // assets/hk-day-lvgl.png
LV_IMG_DECLARE( ui_img_1167879829);   // assets/hk-sunset-lvgl.png
LV_IMG_DECLARE( ui_img_783909477);   // assets/hk-night-lvgl.png

// FONTS
LV_FONT_DECLARE( ui_font_NSTC28bold);
LV_FONT_DECLARE( ui_font_NSTC44bold);
LV_FONT_DECLARE( ui_font_NSTC80bold);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
