// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Bus_ETA

#include "ui.h"
#include "../Display.h"

void NextPage(lv_event_t * e)
{
    OnNextPagePressed();
}
