// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Bus_ETA

#include "ui.h"

lv_obj_t *ui_Main = NULL;lv_obj_t *ui_imgBackgroundDay = NULL;lv_obj_t *ui_imgBackgroundSunset = NULL;lv_obj_t *ui_imgBackgroundNight = NULL;lv_obj_t *ui_ctrLeft = NULL;lv_obj_t *ui_ctrRight = NULL;lv_obj_t *ui_lblNowDate = NULL;lv_obj_t *ui_lblNowTime = NULL;lv_obj_t *ui_lblTemp = NULL;lv_obj_t *ui_lblDC = NULL;lv_obj_t *ui_lblWeather = NULL;lv_obj_t *ui_lblHolidayHeader = NULL;lv_obj_t *ui_lblHolidayInfo = NULL;lv_obj_t *ui_lblHolidayDate = NULL;lv_obj_t *ui_lblWifiInfo = NULL;lv_obj_t *ui_lblETAListHeader = NULL;lv_obj_t *ui_lblRoute1 = NULL;lv_obj_t *ui_lblETA11 = NULL;lv_obj_t *ui_lblETA12 = NULL;lv_obj_t *ui_lblDest1 = NULL;lv_obj_t *ui_lblRoute2 = NULL;lv_obj_t *ui_lblETA21 = NULL;lv_obj_t *ui_lblETA22 = NULL;lv_obj_t *ui_lblDest2 = NULL;lv_obj_t *ui_lblRoute3 = NULL;lv_obj_t *ui_lblETA31 = NULL;lv_obj_t *ui_lblETA32 = NULL;lv_obj_t *ui_lblDest3 = NULL;lv_obj_t *ui_lblRoute4 = NULL;lv_obj_t *ui_lblETA41 = NULL;lv_obj_t *ui_lblETA42 = NULL;lv_obj_t *ui_lblDest4 = NULL;lv_obj_t *ui_ctrTouch = NULL;
// event funtions
void ui_event_ctrTouch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      NextPage( e );
}
}

// build funtions

void ui_Main_screen_init(void)
{
ui_Main = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgBackgroundDay = lv_img_create(ui_Main);
lv_obj_set_width( ui_imgBackgroundDay, 483);
lv_obj_set_height( ui_imgBackgroundDay, 480);
lv_obj_add_flag( ui_imgBackgroundDay, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgBackgroundDay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgBackgroundSunset = lv_img_create(ui_Main);
lv_obj_set_width( ui_imgBackgroundSunset, 483);
lv_obj_set_height( ui_imgBackgroundSunset, LV_SIZE_CONTENT);   /// 480
lv_obj_add_flag( ui_imgBackgroundSunset, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgBackgroundSunset, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgBackgroundNight = lv_img_create(ui_Main);
lv_obj_set_width( ui_imgBackgroundNight, 483);
lv_obj_set_height( ui_imgBackgroundNight, 480);
lv_obj_add_flag( ui_imgBackgroundNight, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgBackgroundNight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ctrLeft = lv_obj_create(ui_Main);
lv_obj_remove_style_all(ui_ctrLeft);
lv_obj_set_width( ui_ctrLeft, 347);
lv_obj_set_height( ui_ctrLeft, 395);
lv_obj_set_x( ui_ctrLeft, 68 );
lv_obj_set_y( ui_ctrLeft, 39 );
lv_obj_clear_flag( ui_ctrLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ctrLeft, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ctrLeft, lv_color_hex(0x180F0F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ctrLeft, 180, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ctrRight = lv_obj_create(ui_Main);
lv_obj_remove_style_all(ui_ctrRight);
lv_obj_set_width( ui_ctrRight, 317);
lv_obj_set_height( ui_ctrRight, 480);
lv_obj_set_x( ui_ctrRight, 483 );
lv_obj_set_y( ui_ctrRight, 0 );
lv_obj_clear_flag( ui_ctrRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ctrRight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ctrRight, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblNowDate = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblNowDate, 347);
lv_obj_set_height( ui_lblNowDate, 39);
lv_obj_set_x( ui_lblNowDate, 68 );
lv_obj_set_y( ui_lblNowDate, 39 );
lv_label_set_text(ui_lblNowDate,"----年--月--日(-)");
lv_obj_set_style_text_color(ui_lblNowDate, lv_color_hex(0xFFFCFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblNowDate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblNowDate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblNowDate, &ui_font_NSTC28bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblNowDate, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblNowDate, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblNowDate, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblNowDate, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblNowTime = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblNowTime, 347);
lv_obj_set_height( ui_lblNowTime, 150);
lv_obj_set_x( ui_lblNowTime, 68 );
lv_obj_set_y( ui_lblNowTime, 78 );
lv_label_set_text(ui_lblNowTime,"--:--");
lv_obj_set_style_text_color(ui_lblNowTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblNowTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblNowTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblNowTime, &ui_font_NSTC80bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblNowTime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblNowTime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblNowTime, 45, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblNowTime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblTemp = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblTemp, 133);
lv_obj_set_height( ui_lblTemp, 67);
lv_obj_set_x( ui_lblTemp, 68 );
lv_obj_set_y( ui_lblTemp, 236 );
lv_label_set_text(ui_lblTemp,"24.5");
lv_obj_set_style_text_color(ui_lblTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblTemp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblTemp, &ui_font_NSTC44bold, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblDC = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblDC, 50);
lv_obj_set_height( ui_lblDC, 67);
lv_obj_set_x( ui_lblDC, 202 );
lv_obj_set_y( ui_lblDC, 236 );
lv_label_set_long_mode(ui_lblDC,LV_LABEL_LONG_CLIP);
lv_label_set_text(ui_lblDC,"°C");
lv_obj_set_style_text_color(ui_lblDC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblDC, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblDC, &ui_font_NSTC44bold, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblWeather = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblWeather, 133);
lv_obj_set_height( ui_lblWeather, 67);
lv_obj_set_x( ui_lblWeather, 277 );
lv_obj_set_y( ui_lblWeather, 236 );
lv_label_set_text(ui_lblWeather,"多雲\n");
lv_obj_set_style_text_color(ui_lblWeather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblWeather, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblWeather, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblWeather, &ui_font_NSTC44bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblWeather, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblWeather, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblWeather, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblWeather, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblHolidayHeader = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblHolidayHeader, 340);
lv_obj_set_height( ui_lblHolidayHeader, 39);
lv_obj_set_x( ui_lblHolidayHeader, 75 );
lv_obj_set_y( ui_lblHolidayHeader, 316 );
lv_label_set_text(ui_lblHolidayHeader,"距離下個公眾假期:");
lv_obj_set_style_text_color(ui_lblHolidayHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblHolidayHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblHolidayHeader, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblHolidayHeader, &ui_font_NSTC28bold, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblHolidayInfo = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblHolidayInfo, 340);
lv_obj_set_height( ui_lblHolidayInfo, 39);
lv_obj_set_x( ui_lblHolidayInfo, 75 );
lv_obj_set_y( ui_lblHolidayInfo, 355 );
lv_label_set_text(ui_lblHolidayInfo,"---還有--天");
lv_obj_set_style_text_color(ui_lblHolidayInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblHolidayInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblHolidayInfo, &ui_font_NSTC28bold, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblHolidayDate = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblHolidayDate, LV_SIZE_CONTENT);  /// 340
lv_obj_set_height( ui_lblHolidayDate, LV_SIZE_CONTENT);   /// 39
lv_obj_set_x( ui_lblHolidayDate, 75 );
lv_obj_set_y( ui_lblHolidayDate, 395 );
lv_label_set_text(ui_lblHolidayDate,"----年--月--日(-)");
lv_obj_set_style_text_color(ui_lblHolidayDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblHolidayDate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblHolidayDate, &ui_font_NSTC28bold, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblWifiInfo = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblWifiInfo, 483);
lv_obj_set_height( ui_lblWifiInfo, 43);
lv_obj_set_x( ui_lblWifiInfo, 0 );
lv_obj_set_y( ui_lblWifiInfo, 450 );
//lv_label_set_long_mode(ui_lblWifiInfo,LV_LABEL_LONG_SCROLL_CIRCULAR);
lv_label_set_text(ui_lblWifiInfo,"");
lv_obj_set_style_text_color(ui_lblWifiInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblWifiInfo, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
//lv_obj_set_style_text_align(ui_lblWifiInfo, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblWifiInfo, &ui_font_NSTC28bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblWifiInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblWifiInfo, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblETAListHeader = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblETAListHeader, 317);
lv_obj_set_height( ui_lblETAListHeader, 46);
lv_obj_set_x( ui_lblETAListHeader, 483 );
lv_obj_set_y( ui_lblETAListHeader, 0 );
lv_label_set_text(ui_lblETAListHeader,"分鐘(min)");
lv_obj_set_style_text_color(ui_lblETAListHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblETAListHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblETAListHeader, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_lblETAListHeader, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblETAListHeader, &ui_font_NSTC28bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblETAListHeader, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblETAListHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblETAListHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblETAListHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblETAListHeader, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblETAListHeader, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblRoute1 = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblRoute1, 143);
lv_obj_set_height( ui_lblRoute1, 67);
lv_obj_set_x( ui_lblRoute1, 483 );
lv_obj_set_y( ui_lblRoute1, 44 );
lv_label_set_text(ui_lblRoute1,"");
lv_obj_set_style_text_color(ui_lblRoute1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblRoute1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblRoute1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblRoute1, &ui_font_NSTC44bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblRoute1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblRoute1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblRoute1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblRoute1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblRoute1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblRoute1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblETA11 = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblETA11, 93);
lv_obj_set_height( ui_lblETA11, 67);
lv_obj_set_x( ui_lblETA11, 623 );
lv_obj_set_y( ui_lblETA11, 44 );
lv_label_set_text(ui_lblETA11,"");
lv_obj_set_style_text_color(ui_lblETA11, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblETA11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblETA11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblETA11, &ui_font_NSTC44bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblETA11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblETA11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblETA12 = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblETA12, 84);
lv_obj_set_height( ui_lblETA12, 67);
lv_obj_set_x( ui_lblETA12, 716 );
lv_obj_set_y( ui_lblETA12, 44 );
lv_label_set_text(ui_lblETA12,"");
lv_obj_set_style_text_color(ui_lblETA12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblETA12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblETA12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblETA12, &ui_font_NSTC44bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblETA12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblETA12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblDest1 = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblDest1, 317);
lv_obj_set_height( ui_lblDest1, 42);
lv_obj_set_x( ui_lblDest1, 483 );
lv_obj_set_y( ui_lblDest1, 110 );
lv_label_set_text(ui_lblDest1,"");
lv_obj_set_style_text_color(ui_lblDest1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblDest1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblDest1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblDest1, &ui_font_NSTC28bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblDest1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblDest1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblDest1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblDest1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblDest1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblDest1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblRoute2 = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblRoute2, 143);
lv_obj_set_height( ui_lblRoute2, 67);
lv_obj_set_x( ui_lblRoute2, 483 );
lv_obj_set_y( ui_lblRoute2, 154 );
lv_label_set_text(ui_lblRoute2,"");
lv_obj_set_style_text_color(ui_lblRoute2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblRoute2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblRoute2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblRoute2, &ui_font_NSTC44bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblRoute2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblRoute2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblRoute2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblRoute2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblRoute2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblRoute2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblETA21 = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblETA21, 93);
lv_obj_set_height( ui_lblETA21, 67);
lv_obj_set_x( ui_lblETA21, 623 );
lv_obj_set_y( ui_lblETA21, 154 );
lv_label_set_text(ui_lblETA21,"");
lv_obj_set_style_text_color(ui_lblETA21, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblETA21, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblETA21, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblETA21, &ui_font_NSTC44bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblETA21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblETA21, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblETA22 = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblETA22, 84);
lv_obj_set_height( ui_lblETA22, 67);
lv_obj_set_x( ui_lblETA22, 716 );
lv_obj_set_y( ui_lblETA22, 154 );
lv_label_set_text(ui_lblETA22,"");
lv_obj_set_style_text_color(ui_lblETA22, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblETA22, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblETA22, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblETA22, &ui_font_NSTC44bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblETA22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblETA22, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblDest2 = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblDest2, 317);
lv_obj_set_height( ui_lblDest2, 42);
lv_obj_set_x( ui_lblDest2, 483 );
lv_obj_set_y( ui_lblDest2, 219 );
lv_label_set_text(ui_lblDest2,"");
lv_obj_set_style_text_color(ui_lblDest2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblDest2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblDest2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblDest2, &ui_font_NSTC28bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblDest2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblDest2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblDest2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblDest2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblDest2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblDest2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblRoute3 = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblRoute3, 143);
lv_obj_set_height( ui_lblRoute3, 67);
lv_obj_set_x( ui_lblRoute3, 483 );
lv_obj_set_y( ui_lblRoute3, 263 );
lv_label_set_text(ui_lblRoute3,"");
lv_obj_set_style_text_color(ui_lblRoute3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblRoute3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblRoute3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblRoute3, &ui_font_NSTC44bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblRoute3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblRoute3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblRoute3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblRoute3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblRoute3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblRoute3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblETA31 = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblETA31, 93);
lv_obj_set_height( ui_lblETA31, 67);
lv_obj_set_x( ui_lblETA31, 623 );
lv_obj_set_y( ui_lblETA31, 263 );
lv_label_set_text(ui_lblETA31,"");
lv_obj_set_style_text_color(ui_lblETA31, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblETA31, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblETA31, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblETA31, &ui_font_NSTC44bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblETA31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblETA31, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblETA32 = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblETA32, 84);
lv_obj_set_height( ui_lblETA32, 67);
lv_obj_set_x( ui_lblETA32, 716 );
lv_obj_set_y( ui_lblETA32, 263 );
lv_label_set_text(ui_lblETA32,"");
lv_obj_set_style_text_color(ui_lblETA32, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblETA32, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblETA32, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblETA32, &ui_font_NSTC44bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblETA32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblETA32, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblDest3 = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblDest3, 317);
lv_obj_set_height( ui_lblDest3, 42);
lv_obj_set_x( ui_lblDest3, 483 );
lv_obj_set_y( ui_lblDest3, 328 );
lv_label_set_text(ui_lblDest3,"");
lv_obj_set_style_text_color(ui_lblDest3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblDest3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblDest3, &ui_font_NSTC28bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblDest3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblDest3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblDest3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblDest3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblDest3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblDest3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblRoute4 = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblRoute4, 143);
lv_obj_set_height( ui_lblRoute4, 67);
lv_obj_set_x( ui_lblRoute4, 483 );
lv_obj_set_y( ui_lblRoute4, 372 );
lv_label_set_text(ui_lblRoute4,"");
lv_obj_set_style_text_color(ui_lblRoute4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblRoute4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblRoute4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblRoute4, &ui_font_NSTC44bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblRoute4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblRoute4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblRoute4, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblRoute4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblRoute4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblRoute4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblETA41 = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblETA41, 93);
lv_obj_set_height( ui_lblETA41, 67);
lv_obj_set_x( ui_lblETA41, 623 );
lv_obj_set_y( ui_lblETA41, 372 );
lv_label_set_text(ui_lblETA41,"");
lv_obj_set_style_text_color(ui_lblETA41, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblETA41, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblETA41, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblETA41, &ui_font_NSTC44bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblETA41, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblETA41, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblETA42 = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblETA42, 84);
lv_obj_set_height( ui_lblETA42, 67);
lv_obj_set_x( ui_lblETA42, 716 );
lv_obj_set_y( ui_lblETA42, 372 );
lv_label_set_text(ui_lblETA42,"");
lv_obj_set_style_text_color(ui_lblETA42, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblETA42, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblETA42, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblETA42, &ui_font_NSTC44bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblETA42, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblETA42, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblDest4 = lv_label_create(ui_Main);
lv_obj_set_width( ui_lblDest4, 317);
lv_obj_set_height( ui_lblDest4, 42);
lv_obj_set_x( ui_lblDest4, 483 );
lv_obj_set_y( ui_lblDest4, 438 );
lv_label_set_text(ui_lblDest4,"");
lv_obj_set_style_text_color(ui_lblDest4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblDest4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_lblDest4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblDest4, &ui_font_NSTC28bold, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_lblDest4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblDest4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_lblDest4, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_lblDest4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_lblDest4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_lblDest4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ctrTouch = lv_obj_create(ui_Main);
lv_obj_remove_style_all(ui_ctrTouch);
lv_obj_set_width( ui_ctrTouch, 317);
lv_obj_set_height( ui_ctrTouch, 480);
lv_obj_set_x( ui_ctrTouch, 483 );
lv_obj_set_y( ui_ctrTouch, 0 );
lv_obj_clear_flag( ui_ctrTouch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ctrTouch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ctrTouch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ctrTouch, ui_event_ctrTouch, LV_EVENT_ALL, NULL);

}

void ui_Main_screen_destroy(void)
{
   if (ui_Main) lv_obj_del(ui_Main);

// NULL screen variables
ui_Main= NULL;
ui_imgBackgroundDay= NULL;
ui_imgBackgroundSunset= NULL;
ui_imgBackgroundNight= NULL;
ui_ctrLeft= NULL;
ui_ctrRight= NULL;
ui_lblNowDate= NULL;
ui_lblNowTime= NULL;
ui_lblTemp= NULL;
ui_lblDC= NULL;
ui_lblWeather= NULL;
ui_lblHolidayHeader= NULL;
ui_lblHolidayInfo= NULL;
ui_lblHolidayDate= NULL;
ui_lblWifiInfo= NULL;
ui_lblETAListHeader= NULL;
ui_lblRoute1= NULL;
ui_lblETA11= NULL;
ui_lblETA12= NULL;
ui_lblDest1= NULL;
ui_lblRoute2= NULL;
ui_lblETA21= NULL;
ui_lblETA22= NULL;
ui_lblDest2= NULL;
ui_lblRoute3= NULL;
ui_lblETA31= NULL;
ui_lblETA32= NULL;
ui_lblDest3= NULL;
ui_lblRoute4= NULL;
ui_lblETA41= NULL;
ui_lblETA42= NULL;
ui_lblDest4= NULL;
ui_ctrTouch= NULL;

}
