// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Bus_ETA

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t *ui_Main;
extern lv_obj_t *ui_imgBackgroundDay;
extern lv_obj_t *ui_imgBackgroundSunset;
extern lv_obj_t *ui_imgBackgroundNight;
extern lv_obj_t *ui_ctrLeft;
extern lv_obj_t *ui_ctrRight;
extern lv_obj_t *ui_lblNowDate;
extern lv_obj_t *ui_lblNowTime;
extern lv_obj_t *ui_lblTemp;
extern lv_obj_t *ui_lblDC;
extern lv_obj_t *ui_lblWeather;
extern lv_obj_t *ui_lblHolidayHeader;
extern lv_obj_t *ui_lblHolidayInfo;
extern lv_obj_t *ui_lblHolidayDate;
extern lv_obj_t *ui_lblWifiInfo;
extern lv_obj_t *ui_lblETAListHeader;
extern lv_obj_t *ui_lblRoute1;
extern lv_obj_t *ui_lblETA11;
extern lv_obj_t *ui_lblETA12;
extern lv_obj_t *ui_lblDest1;
extern lv_obj_t *ui_lblRoute2;
extern lv_obj_t *ui_lblETA21;
extern lv_obj_t *ui_lblETA22;
extern lv_obj_t *ui_lblDest2;
extern lv_obj_t *ui_lblRoute3;
extern lv_obj_t *ui_lblETA31;
extern lv_obj_t *ui_lblETA32;
extern lv_obj_t *ui_lblDest3;
extern lv_obj_t *ui_lblRoute4;
extern lv_obj_t *ui_lblETA41;
extern lv_obj_t *ui_lblETA42;
extern lv_obj_t *ui_lblDest4;
extern void ui_event_ctrTouch( lv_event_t * e);
extern lv_obj_t *ui_ctrTouch;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

