#!/usr/bin/env python3
"""Refresh compact KMB stop names and route-direction records."""

from __future__ import annotations

import json
import urllib.request
from pathlib import Path


API_BASE = "https://data.etabus.gov.hk/v1/transport/kmb"
PROJECT_ROOT = Path(__file__).resolve().parents[1]
STOP_OUTPUT = PROJECT_ROOT / "data" / "kmb-stops.tsv"
ROUTE_OUTPUT = PROJECT_ROOT / "src" / "KmbRouteCacheData.inc"


def fetch(endpoint: str) -> dict:
    request = urllib.request.Request(
        f"{API_BASE}/{endpoint}",
        headers={"User-Agent": "standalone-esp32-dashboard-cache-builder/1.0"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def main() -> None:
    payload = fetch("stop")

    rows: list[tuple[str, str]] = []
    for value in payload.get("data", []):
        stop_id = str(value.get("stop", "")).strip()
        name_tc = str(value.get("name_tc", "")).replace("\t", " ").replace("\n", " ").strip()
        if len(stop_id) == 16 and name_tc:
            rows.append((stop_id, name_tc))

    rows.sort()
    if len(rows) < 6000:
        raise RuntimeError(f"KMB stop response unexpectedly small: {len(rows)} rows")

    STOP_OUTPUT.write_text(
        "".join(f"{stop_id}\t{name_tc}\n" for stop_id, name_tc in rows),
        encoding="utf-8",
    )
    print(
        f"Wrote {len(rows)} KMB stops to {STOP_OUTPUT} "
        f"({STOP_OUTPUT.stat().st_size} bytes)"
    )

    route_payload = fetch("route")
    route_rows: list[tuple[str, str, int, str]] = []
    for value in route_payload.get("data", []):
        route = str(value.get("route", "")).strip().upper()
        direction = str(value.get("bound", "")).strip().upper()
        destination = str(value.get("dest_tc", "")).replace("\t", " ").replace("\n", " ").strip()
        try:
            service_type = int(value.get("service_type", 0))
        except (TypeError, ValueError):
            service_type = 0
        if route and direction in {"I", "O"} and 1 <= service_type <= 3 and destination:
            route_rows.append((route, direction, service_type, destination))

    if len(route_rows) < 700:
        raise RuntimeError(
            f"KMB route response unexpectedly small: {len(route_rows)} rows"
        )

    def quoted(value: str) -> str:
        return json.dumps(value, ensure_ascii=False)

    ROUTE_OUTPUT.write_text(
        "// Generated by scripts/update_kmb_stop_cache.py; do not hand edit.\n"
        + "".join(
            "{" + ", ".join(
                (quoted(route), quoted(direction), str(service_type), quoted(destination))
            ) + "},\n"
            for route, direction, service_type, destination in route_rows
        ),
        encoding="utf-8",
    )
    print(
        f"Wrote {len(route_rows)} KMB directions to {ROUTE_OUTPUT} "
        f"({ROUTE_OUTPUT.stat().st_size} bytes)"
    )


if __name__ == "__main__":
    main()
